version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Back-End/Dockerfile 
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    volumes:
      - ./Back-End:/app/Back-End  
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Front-End/Dockerfile  
    ports:
      - "80:80"
    volumes:
      - ./Front-End:/app/Front-End   
      - ./Front-End/dist:/usr/share/nginx/html  
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
